### PR TITLE
Fixed ReferenceError in case globalThis is undefined.

### PR DESCRIPTION
**Pull request by PysKa-Ratzinger**

### CODE REVIEW

**Comment by Greenheart** [comment]
Hi! Thanks for the PR!

What environment doesn't support `globalThis`?

According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#browser_compatibility, this works in almost all modern JS runtimes.

This project supports Node.js >= 16 and browsers released after 2017.

**Comment by PysKa-Ratzinger** [comment]
Hi!

That is a very good question. I don't know...

The issue I encountered was the exact opposite, with an older version of pagecrypt, where "this" was undefined (somehow). And after fixing the issue locally, I thought the algorithm a bit odd, so I wanted to make it fool-proof for others.

See, if globalThis is ever undefined, but window is not, instead of returning window.crypto, a ReferenceError will be thrown instead. Of course, if globalThis is never undefined, then window.crypto is never used.

Because of this edge-case which I never encountered, I made the PR. I will defer to you whether this brings value to the project.

**Comment by PysKa-Ratzinger** [comment]
PS: Btw, I made another commit to prefer globalThis, since that was what was used originally, and I don't want to break anything, in case window.crypto is somehow different to globalThis.crypto.

**Comment by Greenheart** [comment]
Thanks for this PR! :slightly_smiling_face:

I used your suggested changes as inspiration, but implemented it slightly differently since async functions always wrap their return values in promises, and we thus don't need to do that manually.

I also updated comments to match the new structure. This will be released in the next version.

**Pull request closed without merging**
